package com.skanga.conductor.orchestration;

import com.skanga.conductor.agent.SubAgent;

/**
 * Immutable data transfer object representing the result of sub-agent task execution.
 * <p>
 * This record encapsulates the outcome of a task execution, including the generated
 * output, success status, and optional metadata. It provides a standardized way
 * to return execution results from sub-agents to orchestrators and other components.
 * </p>
 * <p>
 * The output field contains the main result of the task execution, typically text
 * generated by an LLM or produced by tool execution. The success flag indicates
 * whether the task completed successfully or encountered an error. The metadata
 * field can contain additional information about the execution, such as performance
 * metrics, execution context, or error details.
 * </p>
 * <p>
 * As a record, this class is immutable and provides automatic implementations of
 * equals(), hashCode(), toString(), and accessor methods.
 * </p>
 *
 * @param output the main result content from task execution, typically text
 * @param success true if the task completed successfully, false if it failed
 * @param metadata optional additional execution information, can be null
 *
 * @since 1.0.0
 * @see SubAgent#execute(TaskInput)
 * @see TaskInput
 */
public record TaskResult(String output, boolean success, Object metadata) {
}